# Generated by Django 5.2.4 on 2025-07-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=100)),
                ('paragraph_one', models.TextField()),
                ('paragraph_two', models.TextField(blank=True)),
                ('paragraph_three', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
    ]
