# Generated by Django 5.2.4 on 2025-07-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hero_delete_profile_alter_techskill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=300)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('in_development', models.BooleanField(default=False)),
            ],
        ),
    ]
