# Generated by Django 5.2.4 on 2025-07-25 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ponmile Daramola', max_length=100)),
                ('title', models.CharField(default='Full-Stack Developer & Data Analyst', max_length=200)),
                ('description', models.TextField(default="Welcome! I'm a passionate tech enthusiast with expertise in backend development, data analysis, and mobile development. I love building innovative solutions that combine robust engineering with data-driven insights.")),
                ('resume', models.FileField(blank=True, help_text='Upload your resume in PDF format', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('data', 'Data Science')], max_length=20)),
                ('svg_icon', models.TextField(blank=True, help_text='SVG code for the skill icon')),
                ('icon_url', models.URLField(blank=True, help_text='Alternative: URL to icon image')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True, help_text='Show in hero section badges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tech Skill',
                'verbose_name_plural': 'Tech Skills',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
