# Generated by Django 5.2.4 on 2025-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=100)),
                ('paragraph_one', models.TextField()),
                ('paragraph_two', models.TextField(blank=True)),
                ('paragraph_three', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=300)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('in_development', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterModelOptions(
            name='techskill',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='techskill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='techskill',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='techskill',
            name='svg_icon',
        ),
        migrations.AddField(
            model_name='techskill',
            name='icon_svg',
            field=models.TextField(help_text='Paste inline SVG code here', null=True),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('data science', 'Data Science')], default='backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
