# Generated by Django 5.2.4 on 2025-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterModelOptions(
            name='techskill',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='techskill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='techskill',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='techskill',
            name='svg_icon',
        ),
        migrations.AddField(
            model_name='techskill',
            name='icon_svg',
            field=models.TextField(help_text='Paste inline SVG code here', null=True),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('data science', 'Data Science')], default='backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
